version: '3'
services:
  web:
    volumes:
      - '../../../app:/opt/node_app/app'
      - '../../../lib:/opt/node_app/lib'
      - '../../../views:/opt/node_app/views'
      - '../../../public:/opt/node_app/public'
      - '../../../extensions:/opt/node_app/extensions'
      - '../../../db:/opt/node_app/db'
      - '../../../certs:/opt/node_app/certs'
      - '../../../public/assets/Img:/opt/node_app/public/assets/Img:rw'
    ports:
      - '8100:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Development/web/Dockerfile'
    depends_on:
      - 'db'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
  db:
    image: 'postgres:12.4'
    environment:
      POSTGRES_PASSWORD: 'sc2ql0XY'
      POSTGRES_USER: 'db_user'
      POSTGRES_DB: 'taskbit'
    volumes:
      - './db_init:/docker-entrypoint-initdb.d'
    ports:
      - '9906:5432'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
  redis:
    image: 'redis:alpine'
    hostname: 'redis'
    volumes:
      - 'redis-volume:/data'
volumes:
  redis-volume: ~
